### ISSUE TITLE
Strange behaviour with Passthrough

### ISSUE THREAD

**Issue by jdotbdot** [bartbutenaers/node-red-contrib-ui-multistate-switch#15]
Multistate switch, all default values, with two default options. (So Passthrough is "Never", Input msg "All", Passthrough field and Input msg field are both "msg.passthrough")

Inject a message with msg.passthrough = timestamp gives two errors 
"The 'passthrough' message field value should contain 'never', 'always' or 'change' " and 
"The 'input msg' message field value should contain 'none' or 'all' "

Am I misunderstanding message passthrough? I was expecting an injected message to be silently ignored (Passthrough == Never) or to be passed on as if it was a switch event (Passthrough == All)

**Comment by bartbutenaers** [comment]
@jdotbdot,
This has also been reported on [Discourse](https://discourse.nodered.org/t/announce-node-red-contrib-ui-multistate-switch-1-2-0/50464/14?u=bartbutenaers).  I have fixed a few things about passthrough, but it is not published on NPM yet.  Can you please install the version from Github (from within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-ui-multistate-switch
```
And let us know if you still have passthrough issues?
Bart

**Comment by jdotbdot** [comment]
I mentioned it on discourse, hopefully more coherently than here.
Yes, resolved thanks.
