### ISSUE TITLE
User input is still allowed after msg.enabled false

### ISSUE THREAD

**Issue by Hugobox** [bartbutenaers/node-red-contrib-ui-multistate-switch#19]
Hi!
When we send a msg.enabled false to the multiswitch, it effectively becomes greyed out to signify it is disabled, but clicking on the switch still changes the state of the switch.

Thanks!

**Comment by bartbutenaers** [comment]
Hello @Hugobox,

As you can see [here](https://github.com/bartbutenaers/node-red-contrib-ui-multistate-switch#user-input-field) the "msg.enabled" field can have 3 different string values.  So it is not a boolean!  At the beginning of our developments it used to be a boolean, but we changed it quickly afterwards.  See [here](https://github.com/bartbutenaers/node-red-contrib-ui-multistate-switch/wiki/Configuring-the-switch-via-input-messages) for an example flow.

When I test that flow on my Windows 10 portable, then it seems to work fine in Chrome/Firefox/Edge.

Bart

**Comment by Hugobox** [comment]
Ok Good! I missed that! Thanks I will try it soon! Just to let you know that the documentation mentions that using boolean is still valid:
"For legacy reasons, it is also possible to use true as content."

**Comment by Hugobox** [comment]
Ok so after testing, msg.enable (no "d" at the end) with boolean or string as per the documentation works as intended. With msg.enabled (with d at the end) and boolean false as payload, the widget becomes greyed out but can still be interacted with.

**Comment by bartbutenaers** [comment]
Thanks for the analysis.

Did a quick scan in the code of this node, and we use nowhere the `msg.enabled`.  So I was a bit confused...

However in the [documentation](https://github.com/node-red/node-red-dashboard) of the dashboard itself, I now see this information:

> Any widget can be disabled by passing in a msg.enabled property set to false;. Note: this doesn't stop the widget receiving messages but does stop inputs being active and does re-style the widget.

Never seen that before, and never used it.  That is indeed confusing.  Will add it to the documentation.

**Comment by bartbutenaers** [comment]
Done:

![image](https://user-images.githubusercontent.com/14224149/167711407-73feddcd-4c9c-454d-8fd2-10a2ed4961af.png)
