### ISSUE TITLE
Sync state?

### ISSUE THREAD

**Issue by zakx** [bartbutenaers/node-red-contrib-ui-multistate-switch#2]
Hi,

I have multiple devices showing the dashboard UI at the same time.

When I change the multistate switch selection, it is not synced to the other devices. Adding a simple loop from output to input resulted in an endless loop, because the switch seems to forward any message it gets.

Is there any solution for this? Thanks.

I'm running 1.0.0.

Cheers
zakx

**Comment by bartbutenaers** [comment]
Hi @zakx,

Yesterday we have created a fix for this on Github, but it is not on NPM yet.
If you want to test this, you can install the fixed version directly from Github by executing this command within your .node-red folder:
```
npm install bartbutenaers/node-red-contrib-ui-multistate-switch
```
Bart

**Comment by bartbutenaers** [comment]
This is already available on npm since 4 march
