### ISSUE TITLE
Intergration to Home Assistant

### ISSUE THREAD

**Issue by Diesel737** [bartbutenaers/node-red-contrib-ui-multistate-switch#24]
This Multisate Switch will be a great addition with it can be exposed to HA, and the ability to be used on the HA Dashboard.

Do you think that this will be possible in future?

**Comment by bartbutenaers** [comment]
Hi @Diesel737,
Sorry I don't know anything about HomeAssistant.  I use solely Node-RED for my home automation.  You might have more luck if you ask it on the HA forum.
Barr
