### ISSUE TITLE
FR: Alignment options adding 

### ISSUE THREAD

**Issue by IgorTrud** [bartbutenaers/node-red-contrib-ui-multistate-switch#8]
It would be cool to have an alignment options like in Text node.
Component does not look "good" if placed several times under itself.
Left alignment for label and right alignment for switch values would be nice, as an option.

**Comment by hotNipi** [comment]
As for text widget it is easy enough, but here we have much more complex content and we really don't want to create another pile of edge cases. 
But t is deliberately created to be easily overridden.
Add this for dashboard styles override

`<style>
.multistate-switch-label {
    min-width:7em;
}
</style>`

And all labels have at least 7em width. This way you can have even different sizes for different cads. So more freedom than just placement rules.
 
![image](https://user-images.githubusercontent.com/35291460/117705489-c61e7500-b1d4-11eb-9c47-d7f3d4cc26d2.png)

**Comment by bartbutenaers** [comment]
This way of working is now explained in a wiki [tutorial](https://github.com/bartbutenaers/node-red-contrib-ui-multistate-switch/wiki/Align-switches-with-labels-of-different-length).
